export { default as loader } from '~/pages/root/loader.js'
export { default as handle } from '~/pages/root/handle.js'
export { default as links } from '~/pages/root/links.js'
export { default as ErrorBoundary } from '~/pages/root/error.js'
export { default } from '~/pages/root/index.jsx'